services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $pdfGenerationConfigs: '%contao_pdf_generation.configurations%'

    InspiredMinds\ContaoPdfGeneration\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection,ContaoPdfGenerationBundle.php}
